
stages:
  - build-maven
  - security-scanning
  - test

include:
  - template: Code-Quality.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - template: Jobs/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

variables:
  DS_INCLUDE_DEV_DEPENDENCIES: 'false'
  SAST_EXCLUDED_ANALYZERS: gosec,eslint,spotbugs,bandit
  DS_JAVA_VERSION: 8

code_quality:
  stage: build-maven
  services:
  tags:
    - cq-sans-dind
  artifacts:
    paths:
      - gl-code-quality-report.json

sast:
  stage: security-scanning
  needs:
    - build-maven-job
  tags:
    - cq-sans-dind
  variables:
    SAST_EXCLUDED_ANALYZERS: bandit, eslint, gosec, spotbugs

dependency_scanning:
  stage: security-scanning
  needs:
    - build-maven-job
  tags:
    - cq-sans-dind
".secret-analyzer":
  stage: security-scanning
  needs:
    - build-maven-job
  tags:
    - cq-sans-dind
license_scanning:
  stage: security-scanning
  needs:
    - build-maven-job
  tags:
    - cq-sans-dind
build-maven-job:
  stage: build-maven
  script:
    - echo "Compiling the code..."
    - mvn clean verify
    - echo "Compile complete."
  artifacts:
    when: always
    expire_in: 1 week
    reports:
      junit:
        - "*/target/surefire-reports/TEST-*.xml"
        - "*/target/failsafe-reports/TEST-*.xml"
