<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>eu.europa.ec.dynamic-discovery</groupId>
    <artifactId>dynamic-discovery-parent</artifactId>
    <version>2.5-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>dynamic-discovery-parent</name>
    <description>Library for discovering data dynamically based on e-SENS BDXL specification</description>

    <licenses>
        <license>
            <name>LGPL-2.1</name>
            <url>https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <modules>
        <module>dynamic-discovery-client</module>
        <module>dynamic-discovery-cli</module>
    </modules>

    <scm>
        <developerConnection>scm:git:https://ec.europa.eu/digital-building-blocks/code/scm/edelivery/dynamic-discovery-client.git
        </developerConnection>
        <tag>HEAD</tag>
    </scm>

    <distributionManagement>
        <repository>
            <id>cefdigital-releases</id>
            <url>https://ec.europa.eu/digital-building-blocks/artifact/content/repositories/eDelivery/</url>
        </repository>
        <snapshotRepository>
            <id>cefdigital-snapshots</id>
            <url>https://ec.europa.eu/digital-building-blocks/artifact/content/repositories/eDelivery-snapshots/</url>
        </snapshotRepository>
    </distributionManagement>

    <properties>
        <!-- misc properties -->
        <!-- the root/main folder of the project used by aggregation plugins (license). Alternative ${session.executionRootDirectory} -->
        <project.root.baseUri>${maven.multiModuleProjectDirectory}</project.root.baseUri>
        <project.scm.id>edelivery-scm</project.scm.id>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>

        <release.arguments>-Dmaven.javadoc.skip=true -Dmaven.test.skipTests=true -Dmaven.test.skip=true</release.arguments>

        <sonar.binaries>${project.basedir}/target/classes</sonar.binaries>
        <sonar.core.coveragePlugin>jacoco</sonar.core.coveragePlugin>
        <sonar.host.url>http://edelquality.westeurope.cloudapp.azure.com:9000/sonar</sonar.host.url>
        <sonar.jacoco.itReportPath>${project.basedir}/../target/jacoco-it.exec</sonar.jacoco.itReportPath>
        <sonar.jacoco.reportPath>${project.basedir}/target/coverage-reports/jacoco-ut.exec</sonar.jacoco.reportPath>
        <sonar.scm.disabled>true</sonar.scm.disabled>
        <sonar.sources>src/main/java</sonar.sources>
        <surefire.argLine>-Xmx1G</surefire.argLine>

        <!-- dependencies -->
        <bouncycastle.version>1.83</bouncycastle.version>
        <commons-cli.version>1.11.0</commons-cli.version>
        <commons-lang3.version>3.20.0</commons-lang3.version>
        <dnsjava.version>3.6.3</dnsjava.version>
        <hamcrest.version>2.2</hamcrest.version>
        <httpclient.version>5.3.1</httpclient.version>
        <jakarta.xml.bind-api.version>2.3.3</jakarta.xml.bind-api.version>
        <jaxb-api.version>2.3.1</jaxb-api.version>
        <junit-platform-surefire-provider.version>1.3.2</junit-platform-surefire-provider.version>
        <junit.version>5.14.2</junit.version>
        <mockito.version>4.11.0</mockito.version>
        <net.bytebuddy.version>1.18.3</net.bytebuddy.version>
        <org.eclipse.jetty.version>9.4.58.v20250814</org.eclipse.jetty.version>
        <org.glassfish.jaxb.jaxb-runtime.version>2.3.9</org.glassfish.jaxb.jaxb-runtime.version>
        <saxon-he.version>12.4</saxon-he.version>
        <slf4j.version>2.0.17</slf4j.version>
        <spring-test.version>5.3.39</spring-test.version>
        <!-- plugins -->
        <plugin.dependency-check-maven.version>11.1.0</plugin.dependency-check-maven.version>
        <plugin.jacoco-maven-plugin.version>0.8.14</plugin.jacoco-maven-plugin.version>
        <plugin.jaxb2-maven-plugin.version>2.5.0</plugin.jaxb2-maven-plugin.version>
        <plugin.jbuild-helper-maven-plugin.version>1.12</plugin.jbuild-helper-maven-plugin.version>
        <plugin.license-maven-plugin.version>2.7.1</plugin.license-maven-plugin.version>
        <plugin.maven-assembly-plugin.version>3.8.0</plugin.maven-assembly-plugin.version>
        <plugin.maven-compiler-plugin.version>3.14.1</plugin.maven-compiler-plugin.version>
        <plugin.maven-failsafe-plugin.version>3.5.4</plugin.maven-failsafe-plugin.version>
        <plugin.maven-jar-plugin.version.version>3.5.0</plugin.maven-jar-plugin.version.version>
        <plugin.maven-release-plugin.version>3.1.1</plugin.maven-release-plugin.version>
        <plugin.versions-maven-plugin.version>2.20.1</plugin.versions-maven-plugin.version>
        <plugin.maven-shade-plugin.version>3.6.1</plugin.maven-shade-plugin.version>
        <plugin.maven-surefire-plugin.version>3.5.4</plugin.maven-surefire-plugin.version>
        <plugin.xml-maven-plugin.version>1.1.0</plugin.xml-maven-plugin.version>
        <!-- latest version compatible with SonarQube 5.6 -->
        <plugin.sonar.version>3.11.0.3922</plugin.sonar.version>
        <plugin.maven-source-plugin.version>3.4.0</plugin.maven-source-plugin.version>

    </properties>

    <profiles>
        <profile>
            <id>dependency-check</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.owasp</groupId>
                        <artifactId>dependency-check-maven</artifactId>
                        <version>${plugin.dependency-check-maven.version}</version>
                        <configuration>
                            <nvdApiServerId>edelivery-owasp</nvdApiServerId>
                            <!-- Disable .Net Assembly Analyzer -->
                            <assemblyAnalyzerEnabled>false</assemblyAnalyzerEnabled>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>aggregate</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>dependency-license-check</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>license-maven-plugin</artifactId>
                         <executions>
                            <execution>
                                <id>download-licenses</id>
                                <goals>
                                    <goal>aggregate-download-licenses</goal>
                                    <goal>aggregate-add-third-party</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <licenseMerges>
                                <licenseMerge>Apache License, Version 2.0
                                    |Apache Software Licenses
                                    |Apache Software License - Version 2.0
                                    |Apache License 2.0
                                    |Apache 2.0
                                    |Apache-2.0
                                    |Similar to Apache License but with the acknowledgment clause removed
                                    |Apache License|The Apache Software License, Version 2.0
                                    |Apache Public License 2.0|Apache 2|Apache License, version 2.0
                                    |The Apache License, Version 2.0
                                </licenseMerge>
                                <!--  Common Public License Version 1.0|CPL was replaced by Eclipse Public License -->
                                <licenseMerge>Eclipse Public License 1.0/2.0 (EPL-1.0/2.0)
                                    |Eclipse Public License 1.0 (EPL-1.0)
                                    |Eclipse Public License, Version 1.0
                                    |EPL 2.0
                                    |Eclipse Distribution License v. 1.0
                                    |Eclipse Public License (EPL) v1.0
                                    |Eclipse Public License - v 1.0
                                    |Eclipse Distribution License - v 1.0
                                    |Eclipse Public License 1.0
                                    |EDL 1.0
                                    |Common Public License Version 1.0
                                    |CPL
                                    |MPL 2.0 or EPL 1.0
                                </licenseMerge>
                                <licenseMerge>The MIT License|MIT License</licenseMerge>
                                <licenseMerge>BSD license (all versions)
                                    |http://jaxen.codehaus.org/license.html
                                    |BSD-2-Clause|The BSD 3-Clause License
                                    |BSD
                                    |The New BSD License
                                    |BSD License
                                    |The BSD License
                                    |BSD 3-clause New License
                                    |BSD Licence 3
                                    |3-Clause BSD License
                                    |BSD-Style License
                                    |BSD-3-Clause
                                    |New BSD License
                                </licenseMerge>
                                <licenseMerge>Dual license consisting of the CDDL v1.1 and GPL v2
                                    |CDDL+GPLv2
                                    |CDDL + GPLv2 with classpath exception
                                    |CDDL/GPLv2+CE
                                    |CDDL+GPL License
                                </licenseMerge>
                                <licenseMerge>Common Development and Distribution License (CDDL) (all versions)
                                    |COMMON DEVELOPMENT AND DISTRIBUTION LICENSE (CDDL) Version 1.0
                                    |Common Development and Distribution License (CDDL) v1.0
                                    |Common Development and Distribution License (CDDL)
                                    |Common Development and Distribution License
                                    |Common Development and Distribution
                                    |CDDL 1.1|
                                </licenseMerge>
                                <!-- https://hibernate.org/community/license/ - hibernate label it as GNU Library General Public License v2.1 == GNU Lesser General Public License version 2.1  -->
                                <licenseMerge>GNU Lesser General Public License
                                    |GNU Lesser General Public License, version 2.1
                                    |GNU Library General Public License v2.1 or later
                                    |LGPL-2.1
                                    |LGPL
                                </licenseMerge>
                            </licenseMerges>
                            <failOnMissing>true</failOnMissing>
                            <failOnBlacklist>true</failOnBlacklist>
                            <!--  MUST not include EUPL since this is released under LGPL-->
                            <includedLicenses>
                                Apache License, Version 2.0|
                                Eclipse Public License 1.0/2.0 (EPL-1.0/2.0)|
                                The MIT License|
                                BSD license (all versions)|
                                Dual license consisting of the CDDL v1.1 and GPL v2|
                                Common Development and Distribution License (CDDL) (all versions)|
                                GNU Lesser General Public License|
                                Bouncy Castle Licence|
                            </includedLicenses>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>update-license-headers</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>license-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>update-license</id>
                                <goals>
                                    <goal>update-file-header</goal>
                                </goals>
                                <phase>process-sources</phase>
                                <configuration>
                                    <licenseResolver>file://${project.root.baseUri}/license</licenseResolver>
                                    <licenseName>lgpl-2.1</licenseName>
                                    <inceptionYear>2016</inceptionYear>
                                    <organizationName>European Commission | eDelivery | Dynamic Discovery Client</organizationName>
                                    <addJavaLicenseAfterPackage>false</addJavaLicenseAfterPackage>
                                    <processStartTag>#%L</processStartTag>
                                    <processEndTag>#L%</processEndTag>
                                    <sectionDelimiter>%%</sectionDelimiter>
                                    <extraExtensions>
                                        <xjb>xml</xjb>
                                    </extraExtensions>
                                    <includes>
                                        <include>**/*.java</include>
                                        <include>**/*.xml</include>
                                        <include>**/*.xsd</include>
                                        <include>**/*.xjb</include>
                                        <include>**/*.properties</include>
                                        <include>**/*.txt</include>
                                    </includes>
                                    <excludes>
                                        <exclude>**/src/main/resources/xsd/**</exclude>
                                    </excludes>
                                    <roots>
                                        <root>src/main</root>
                                        <root>src/test</root>
                                    </roots>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <!-- Generate NOTICE.md file from licenses.xml
            The plugin will download all licenses from the dependencies and
            generate a target/generated-resources/licenses.xml file with
            org.codehaus.mojo:license-maven-plugin.
            Then it will transform the licenses.xml file to a NOTICE.md file
            with org.codehaus.mojo:xml-maven-plugin and the licenses/config/license.xsl stylesheet.

            To generate the NOTICE.md file, run the following command:

            mvn clean process-resources -Plicense-generate-notice

            NOTE: do not forget to regenerate the NOTICE.md file when adding new dependencies or updating the existing ones
            and before the release!
            -->
            <id>license-generate-notice</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>license-maven-plugin</artifactId>
                        <version>${plugin.license-maven-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>download-licenses</id>
                                <phase>process-resources</phase>
                                <goals>
                                    <goal>aggregate-download-licenses</goal>
                                    <goal>aggregate-add-third-party</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <cleanLicensesOutputDirectory>true</cleanLicensesOutputDirectory>
                            <removeOrphanLicenseFiles>true</removeOrphanLicenseFiles>
                            <excludedGroups>com.smartbear.*|eu.europa.ec.*</excludedGroups>
                            <excludeTransitiveDependencies>true</excludeTransitiveDependencies>
                            <excludedScopes>test</excludedScopes>
                            <includeTransitiveDependencies>false</includeTransitiveDependencies>
                            <sortArtifactByName>true</sortArtifactByName>
                            <licenseMerges>
                                <licenseMerge>Apache-2.0|Apache License, Version 2.0|Apache License 2.0|The Apache Software License, Version 2.0|Apache Public License 2.0|Apache 2|Apache License, version 2.0|The Apache License, Version 2.0|Apache 2.0</licenseMerge>
                                <!--  Common Public License Version 1.0|CPL was replaced by Eclipse Public License -->
                                <licenseMerge>EPL-2.0|EPL 2.0|Eclipse Public License 2.0</licenseMerge>
                                <licenseMerge>EPL-1.0| (EPL-1.0)|Eclipse Public License (EPL) v1.0|Eclipse Public License (EPL), Version 1.0|Eclipse Public License - v 1.0|Eclipse Public License 1.0|EDL 1.0|Common Public License Version 1.0|CPL</licenseMerge>
                                <licenseMerge>GPL-2.0-or-later|The GNU General Public License, v2 with Universal FOSS Exception, v1.0</licenseMerge>
                                <licenseMerge>MIT|The MIT License|MIT License</licenseMerge>
                                <licenseMerge>BSD-3-Clause|BSD license (all versions)|BSD License|The BSD License|BSD 3-clause New License|BSD Licence 3|BSD-Style License|New BSD License|Eclipse Distribution License - v 1.0|Eclipse Distribution License (EDL), Version 1.0</licenseMerge>
                                <licenseMerge>LGPL-2.1+|GNU Library General Public License v2.1 or later|GNU Lesser General Public License</licenseMerge>
                                <licenseMerge>CDDL-1.1|Dual license consisting of the CDDL v1.1 and GPL v2|CDDL + GPLv2 with classpath exception|CDDL/GPLv2+CE|CDDL+GPL License</licenseMerge>
                                <licenseMerge>CDDL-1.0|Common Development and Distribution License (CDDL)|Common Development and Distribution License (CDDL) v1.0|Common Development and Distribution|CDDL 1.1|</licenseMerge>
                            </licenseMerges>
                            <excludedLicenses>
                                <excludedLicense>Unknown license</excludedLicense>
                                <excludedLicense>licenseB</excludedLicense>
                            </excludedLicenses>
                        </configuration>
                    </plugin>

                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>xml-maven-plugin</artifactId>
                        <version>${plugin.xml-maven-plugin.version}</version>
                        <inherited>false</inherited>
                        <executions>
                            <execution>
                                <phase>process-resources</phase>
                                <goals>
                                    <goal>transform</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <catalogHandling>local</catalogHandling>
                            <catalogs>
                                <catalog>license/third-party-licenses/Apache-2.0.txt</catalog>
                            </catalogs>
                            <transformationSets>
                                <transformationSet>
                                    <dir>target/generated-resources/</dir>
                                    <includes>
                                        <include>licenses.xml</include>
                                    </includes>
                                    <stylesheet>license/config/license.xsl</stylesheet>
                                    <outputDir>./</outputDir>

                                    <fileMappers>
                                        <fileMapper implementation="org.codehaus.plexus.components.io.filemappers.RegExpFileMapper">
                                            <pattern>licenses.xml</pattern>
                                            <replacement>Notice.md</replacement>
                                        </fileMapper>
                                    </fileMappers>
                                    <parameters>
                                        <parameter>
                                            <!-- This is external stylesheet parameter set in pom.xml plugin configuration
                                            to include the licenses in the notice file. The value of this parameter is a
                                            comma separated list of licenses as exampled: Apache-2.0,MIT.
                                            Make sure to include the license files in the license/third-party-licenses/${license}.txt
                                            -->
                                            <name>IncludeLicenses</name>
                                            <value>Apache-2.0,BSD-2-Clause,EPL-1.0,EPL-2.0,GPL-2.0-or-later,LGPL-2.1+,MIT</value>
                                        </parameter>
                                    </parameters>
                                </transformationSet>
                            </transformationSets>
                        </configuration>
                        <dependencies>
                            <!-- Enable XSLT 2.0 with this dependency -->
                            <dependency>
                                <groupId>net.sf.saxon</groupId>
                                <artifactId>Saxon-HE</artifactId>
                                <version>${saxon-he.version}</version>
                            </dependency>
                        </dependencies>
                    </plugin>

                </plugins>
            </build>
        </profile>
    </profiles>

    <!-- Default version numbers to use -->
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>dynamic-discovery-client</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>dnsjava</groupId>
                <artifactId>dnsjava</artifactId>
                <version>${dnsjava.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.httpcomponents.client5</groupId>
                <artifactId>httpclient5</artifactId>
                <version>${httpclient.version}</version>
            </dependency>

            <dependency>
                <groupId>org.bouncycastle</groupId>
                <artifactId>bcpkix-jdk18on</artifactId>
                <version>${bouncycastle.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>${commons-lang3.version}</version>
            </dependency>
            <dependency>
                <groupId>commons-cli</groupId>
                <artifactId>commons-cli</artifactId>
                <version>${commons-cli.version}</version>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-simple</artifactId>
                <version>${slf4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>${slf4j.version}</version>
            </dependency>
            <!-- jaxb implementation for cli packaging. -->
            <dependency>
                <groupId>jakarta.xml.bind</groupId>
                <artifactId>jakarta.xml.bind-api</artifactId>
                <version>${jakarta.xml.bind-api.version}</version>
            </dependency>
            <dependency>
                <groupId>org.glassfish.jaxb</groupId>
                <artifactId>jaxb-runtime</artifactId>
                <version>${org.glassfish.jaxb.jaxb-runtime.version}</version>
            </dependency>

            <!-- test dependencies-->
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-core</artifactId>
                <version>${mockito.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-junit-jupiter</artifactId>
                <version>${mockito.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-inline</artifactId>
                <version>${mockito.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-engine</artifactId>
                <version>${junit.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-params</artifactId>
                <version>${junit.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.hamcrest</groupId>
                <artifactId>hamcrest</artifactId>
                <version>${hamcrest.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-test</artifactId>
                <version>${spring-test.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-server</artifactId>
                <version>${org.eclipse.jetty.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-servlet</artifactId>
                <version>${org.eclipse.jetty.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>net.bytebuddy</groupId>
                <artifactId>byte-buddy</artifactId>
                <version>${net.bytebuddy.version}</version>
            </dependency>
            <dependency>
                <groupId>net.bytebuddy</groupId>
                <artifactId>byte-buddy-agent</artifactId>
                <version>${net.bytebuddy.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>


    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>${plugin.maven-jar-plugin.version.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-assembly-plugin</artifactId>
                    <version>${plugin.maven-assembly-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-release-plugin</artifactId>
                    <version>${plugin.maven-release-plugin.version}</version>
                    <configuration>
                        <autoVersionSubmodules>true</autoVersionSubmodules>
                        <useReleaseProfile>false</useReleaseProfile>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>versions-maven-plugin</artifactId>
                    <version>${plugin.versions-maven-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${plugin.maven-surefire-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.owasp</groupId>
                    <artifactId>dependency-check-maven</artifactId>
                    <version>${dependency-check-maven.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>license-maven-plugin</artifactId>
                    <version>${plugin.license-maven-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${plugin.maven-compiler-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>jaxb2-maven-plugin</artifactId>
                    <version>${plugin.jaxb2-maven-plugin.version}</version>
                    <!--add for building it with jdk9+ -->
                    <dependencies>
                        <dependency>
                            <groupId>jakarta.xml.bind</groupId>
                            <artifactId>jakarta.xml.bind-api</artifactId>
                            <version>${jakarta.xml.bind-api.version}</version>
                        </dependency>
                        <dependency>
                            <groupId>org.glassfish.jaxb</groupId>
                            <artifactId>jaxb-xjc</artifactId>
                            <version>${org.glassfish.jaxb.jaxb-runtime.version}</version>
                        </dependency>
                        <dependency>
                            <groupId>org.glassfish.jaxb</groupId>
                            <artifactId>jaxb-runtime</artifactId>
                            <version>${org.glassfish.jaxb.jaxb-runtime.version}</version>
                        </dependency>
                    </dependencies>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>build-helper-maven-plugin</artifactId>
                    <version>${plugin.jbuild-helper-maven-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.jacoco</groupId>
                    <artifactId>jacoco-maven-plugin</artifactId>
                    <version>${plugin.jacoco-maven-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.sonarsource.scanner.maven</groupId>
                    <artifactId>sonar-maven-plugin</artifactId>
                    <version>${plugin.sonar.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <version>${plugin.maven-failsafe-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-shade-plugin</artifactId>
                    <version>${plugin.maven-shade-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>${plugin.maven-source-plugin.version}</version>
                    <executions>
                        <execution>
                            <id>attach-sources</id>
                            <goals>
                                <goal>jar-no-fork</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-release-plugin</artifactId>
                <configuration>
                    <arguments>-Dmaven.javadoc.skip=true -Dmaven.test.skipTests=true -Dmaven.test.skip=true</arguments>
                    <!-- Automatically assign submodules the parent version during the release. -->
                    <autoVersionSubmodules>true</autoVersionSubmodules>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <!--To update only bugfix versions mvn versions:update-properties -DallowSnapshots=false -DallowMajorUpdates=false -DallowMinorUpdates=false -->
                <!--To update minor versions mvn versions:update-properties -DallowSnapshots=false -DallowMajorUpdates=false  -->
                <configuration>
                    <!-- ignore non numeric versions!-->
                    <ignoredVersions>(?i).*-(alpha|beta|m|rc)([-.]?\d+)?</ignoredVersions>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
